# Generated by Django 5.2.17 on 2026-08-28 22:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('NON_CONFORME', 'Produit non conforme'), ('ENDOMMAGE', 'Produit endommage'), ('INCOMPLET', 'Commande incomplete'), ('NON_RECU', 'Jamais recu')], max_length=15)),
                ('description', models.TextField()),
                ('preuves_urls', models.TextField(blank=True, help_text='URLs separees par des virgules.')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', "En cours d'examen"), ('RESOLU', 'Resolu'), ('REJETE', 'Rejete')], default='OUVERT', max_length=10)),
                ('resolution', models.TextField(blank=True)),
                ('montant_rembourse_centimes', models.PositiveIntegerField(default=0)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('admin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_traites', to='comptes.administrateur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='comptes.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='commandes.commande')),
            ],
            options={
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField()),
                ('lien_action', models.CharField(blank=True, max_length=200)),
                ('canal', models.CharField(choices=[('IN_APP', "Dans l'application"), ('EMAIL', 'Courriel'), ('PUSH', 'Notification poussee')], default='IN_APP', max_length=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible', models.CharField(choices=[('PRODUIT', 'Produit'), ('VENDEUR', 'Boutique'), ('LIVREUR', 'Livreur')], max_length=10)),
                ('id_cible', models.PositiveIntegerField()),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('statut_moderation', models.CharField(choices=[('PUBLIE', 'Publie'), ('SIGNALE', 'Signale'), ('MASQUE', 'Masque')], default='PUBLIE', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='comptes.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'indexes': [models.Index(fields=['cible', 'id_cible'], name='engagement__cible_fbbaf9_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'commande', 'cible', 'id_cible'), name='un_avis_par_cible')],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('type_objet', models.CharField(max_length=60)),
                ('id_objet', models.PositiveIntegerField(blank=True, null=True)),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entree du journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['type_objet', 'id_objet'], name='engagement__type_ob_91db7b_idx')],
            },
        ),
    ]
