# Generated by Django 5.2.17 on 2026-08-28 22:43

import comptes.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, help_text='Domicile, Bureau…', max_length=60)),
                ('rue', models.CharField(max_length=200)),
                ('complement', models.CharField(blank=True, max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('pays', models.CharField(default='France', max_length=60)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('instructions_livraison', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='AdresseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_principale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('consentement_marketing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_gestionnaire', models.CharField(choices=[('STAFF_VENDEUR', "Personnel d'un vendeur"), ('STAFF_ENTREPOT', "Personnel d'un entrepot")], max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule', models.CharField(choices=[('VELO', 'Velo'), ('SCOOTER', 'Scooter'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette')], default='VELO', max_length=15)),
                ('mode_livraison', models.CharField(choices=[('EXPRESS', 'Express'), ('STANDARD', 'Standard')], max_length=10)),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=15)),
                ('statut_disponibilite', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_COURSE', 'En course'), ('HORS_LIGNE', 'Hors ligne')], default='HORS_LIGNE', max_length=15)),
                ('position_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('position_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'livreur',
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=150)),
                ('type_activite', models.CharField(choices=[('EXPRESS', 'Express'), ('STANDARD', 'Standard')], max_length=10)),
                ('rayon_livraison_km', models.DecimalField(decimal_places=2, default=5, help_text="Express uniquement : au-dela, la boutique n'apparait pas au catalogue.", max_digits=5)),
                ('siret', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=15)),
                ('compte_stripe_id', models.CharField(blank=True, max_length=100)),
                ('taux_commission', models.DecimalField(decimal_places=4, default=0.15, help_text='Part prelevee par la plateforme, en fraction (0.15 = 15 %).', max_digits=5)),
            ],
            options={
                'verbose_name': 'vendeur',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('VENDEUR', 'Vendeur'), ('GESTIONNAIRE', 'Gestionnaire'), ('LIVREUR', 'Livreur'), ('ADMIN', 'Administrateur')], max_length=20)),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('SUSPENDU', 'Suspendu'), ('DESACTIVE', 'Desactive')], default='ACTIF', max_length=25)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_inscription'],
            },
            managers=[
                ('objects', comptes.models.GestionnaireUtilisateur()),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('ADMIN', 'Administrateur'), ('SUPER_ADMIN', 'Super administrateur')], default='ADMIN', max_length=15)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'administrateur',
            },
        ),
    ]
