# Generated by Django 5.2.17 on 2026-08-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresses', to='livraisons.zonelivraison'),
        ),
        migrations.AddField(
            model_name='adresseclient',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.adresse'),
        ),
        migrations.AddField(
            model_name='client',
            name='adresses',
            field=models.ManyToManyField(related_name='clients', through='comptes.AdresseClient', to='comptes.adresse'),
        ),
        migrations.AddField(
            model_name='client',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adresseclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.client'),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='livraisons.entrepot'),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_gestionnaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livreur',
            name='entrepot',
            field=models.ForeignKey(blank=True, help_text="Standard uniquement : l'entrepot de rattachement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs', to='livraisons.entrepot'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques', to='comptes.adresse'),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_vendeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='comptes.vendeur'),
        ),
        migrations.AddConstraint(
            model_name='adresseclient',
            constraint=models.UniqueConstraint(fields=('client', 'adresse'), name='adresse_unique_par_client'),
        ),
        migrations.AddConstraint(
            model_name='adresseclient',
            constraint=models.UniqueConstraint(condition=models.Q(('est_principale', True)), fields=('client',), name='une_seule_adresse_principale'),
        ),
        migrations.AddConstraint(
            model_name='gestionnaire',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entrepot__isnull', True), ('type_gestionnaire', 'STAFF_VENDEUR'), ('vendeur__isnull', False)), models.Q(('entrepot__isnull', False), ('type_gestionnaire', 'STAFF_ENTREPOT'), ('vendeur__isnull', True)), _connector='OR'), name='gestionnaire_rattache_a_un_seul_cote'),
        ),
    ]
