# Generated by Django 5.2.17 on 2026-08-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('montant_ht_centimes', models.PositiveIntegerField()),
                ('montant_ttc_centimes', models.PositiveIntegerField()),
                ('taux_tva', models.DecimalField(decimal_places=4, default=0.2, max_digits=5)),
                ('url_pdf', models.URLField(blank=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='commandes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_centimes', models.PositiveIntegerField()),
                ('methode', models.CharField(default='CARTE', max_length=30)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('AUTORISE', 'Autorise'), ('CAPTURE', 'Capture'), ('ECHOUE', 'Echoue'), ('REMBOURSE', 'Rembourse')], default='EN_ATTENTE', max_length=12)),
                ('reference_stripe', models.CharField(blank=True, db_index=True, max_length=120)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='commandes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type_reduction', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT', 'Montant fixe'), ('FRAIS_LIVRAISON', 'Frais de livraison offerts')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_minimum_centimes', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite_max', models.PositiveIntegerField(blank=True, null=True)),
                ('quantite_utilisee', models.PositiveIntegerField(default=0)),
                ('cumulable', models.BooleanField(default=False)),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='comptes.vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_centimes', models.PositiveIntegerField()),
                ('motif', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TOTAL', 'Total'), ('PARTIEL', 'Partiel')], max_length=10)),
                ('reference_stripe', models.CharField(blank=True, max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('declenche_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='paiements.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='RepartitionVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_vendeur_centimes', models.PositiveIntegerField()),
                ('montant_commission_centimes', models.PositiveIntegerField()),
                ('reference_transfert_stripe', models.CharField(blank=True, max_length=120)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='paiements.paiement')),
                ('sous_commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repartition', to='commandes.souscommande')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartitions', to='comptes.vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisationPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_applique_centimes', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_appliquees', to='commandes.commande')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='paiements.promotion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('promotion', 'commande'), name='promotion_une_fois_par_commande')],
            },
        ),
    ]
