# Generated by Django 5.2.17 on 2026-08-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=20, unique=True)),
                ('type_service', models.CharField(choices=[('EXPRESS', 'Express'), ('STANDARD', 'Standard')], max_length=10)),
                ('statut_actuel', models.CharField(choices=[('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAYEE', 'Payee'), ('EN_PREPARATION', 'En preparation'), ('PRETE', 'Prete'), ('EXPEDIEE_ENTREPOT', "Expediee vers l'entrepot"), ('RECUE_ENTREPOT', "Recue a l'entrepot"), ('EN_TOURNEE', 'En tournee'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livree'), ('ANNULEE', 'Annulee'), ('REMBOURSEE', 'Remboursee'), ('ECHEC_LIVRAISON', 'Echec de livraison')], default='EN_ATTENTE_PAIEMENT', max_length=25)),
                ('montant_produits_centimes', models.PositiveIntegerField(default=0)),
                ('montant_livraison_centimes', models.PositiveIntegerField(default=0)),
                ('montant_remise_centimes', models.PositiveIntegerField(default=0)),
                ('montant_total_centimes', models.PositiveIntegerField(default=0)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_estimee', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('COMMANDE', 'Commande'), ('LIVRAISON', 'Livraison')], max_length=12)),
                ('id_objet', models.PositiveIntegerField()),
                ('statut_avant', models.CharField(blank=True, max_length=25)),
                ('statut_apres', models.CharField(max_length=25)),
                ('commentaire', models.TextField(blank=True)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit_capture', models.CharField(max_length=200)),
                ('prix_unitaire_centimes', models.PositiveIntegerField()),
                ('quantite', models.PositiveIntegerField()),
                ('sous_total_centimes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_capture_centimes', models.PositiveIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_session', models.CharField(blank=True, db_index=True, max_length=64)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CONVERTI', 'Converti en commande'), ('ABANDONNE', 'Abandonne')], default='ACTIF', max_length=12)),
            ],
            options={
                'ordering': ['-date_maj'],
            },
        ),
        migrations.CreateModel(
            name='SousCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_preparation', models.CharField(choices=[('A_PREPARER', 'A preparer'), ('EN_PREPARATION', 'En preparation'), ('PRETE', 'Prete'), ('EXPEDIEE', 'Expediee'), ('ANNULEE', 'Annulee')], default='A_PREPARER', max_length=15)),
                ('montant_vendeur_centimes', models.PositiveIntegerField(default=0)),
                ('montant_commission_centimes', models.PositiveIntegerField(default=0)),
                ('date_expedition_entrepot', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
