# Generated by Django 5.2.17 on 2026-08-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('commandes', '0001_initial'),
        ('comptes', '0001_initial'),
        ('livraisons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='comptes.adresse'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='comptes.client'),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_de_statut', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='comptes.client'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.panier'),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='commandes.panier'),
        ),
        migrations.AddField(
            model_name='souscommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_commandes', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='souscommande',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_recus', to='livraisons.entrepot'),
        ),
        migrations.AddField(
            model_name='souscommande',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sous_commandes', to='comptes.vendeur'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='sous_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.souscommande'),
        ),
        migrations.AddIndex(
            model_name='historiquestatut',
            index=models.Index(fields=['type_objet', 'id_objet'], name='commandes_h_type_ob_07e8f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.UniqueConstraint(fields=('panier', 'produit'), name='un_produit_par_ligne'),
        ),
        migrations.AddConstraint(
            model_name='souscommande',
            constraint=models.UniqueConstraint(fields=('commande', 'vendeur'), name='un_vendeur_une_fois_par_commande'),
        ),
    ]
