# Generated by Django 5.2.17 on 2026-08-28 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_notification', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('NOTIFIEE', 'Notifiee'), ('ANNULEE', 'Annulee')], default='EN_ATTENTE', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VENTE', 'Vente'), ('REAPPRO', 'Reapprovisionnement'), ('AJUSTEMENT', 'Ajustement manuel'), ('ANNULATION', 'Annulation de commande'), ('RETOUR', 'Retour')], max_length=15)),
                ('quantite', models.IntegerField(help_text='Signee : negative pour une sortie.')),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('stock_apres', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('texte_alternatif', models.CharField(blank=True, help_text="Lu par les lecteurs d'ecran. Rempli automatiquement si vide.", max_length=200)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_unitaire_centimes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image_principale_url', models.URLField(blank=True)),
                ('poids_grammes', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('stock_reserve', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('est_visible', models.BooleanField(default=True, help_text='Masquage par le vendeur.')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'produit',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
