# Generated by Django 5.2.17 on 2026-08-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertedisponibilite',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='catalogue.categorie'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalogue.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='comptes.vendeur'),
        ),
        migrations.AddField(
            model_name='photoproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='alertedisponibilite',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='catalogue.produit'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(condition=models.Q(('stock_reserve__lte', models.F('stock_disponible'))), name='stock_reserve_inferieur_au_disponible'),
        ),
        migrations.AddConstraint(
            model_name='photoproduit',
            constraint=models.UniqueConstraint(fields=('produit', 'ordre'), name='ordre_photo_unique'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'AJUSTEMENT'), _negated=True), models.Q(('motif', ''), _negated=True), _connector='OR'), name='ajustement_exige_un_motif'),
        ),
        migrations.AddConstraint(
            model_name='alertedisponibilite',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'EN_ATTENTE')), fields=('produit', 'utilisateur'), name='une_alerte_active_par_produit_et_personne'),
        ),
    ]
