# Generated by Django 5.2.17 on 2026-08-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproduit',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_principale_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
