# Generated by Django 5.2.17 on 2026-08-28 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots', to='comptes.adresse')),
            ],
            options={
                'verbose_name': 'entrepot',
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PRETE', 'Prete'), ('AFFECTEE', 'Affectee'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminee')], default='BROUILLON', max_length=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('nombre_arrets', models.PositiveIntegerField(default=0)),
                ('distance_totale_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees_creees', to='comptes.gestionnaire')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='livraisons.entrepot')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='comptes.livreur')),
            ],
            options={
                'verbose_name': 'tournee',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_livraison', models.CharField(choices=[('A_ATTRIBUER', 'A attribuer'), ('ATTRIBUEE', 'Attribuee'), ('RECUPEREE', 'Colis recupere'), ('EN_ROUTE', 'En route'), ('LIVREE', 'Livree'), ('ECHOUEE', 'Echouee'), ('ANNULEE', 'Annulee')], default='A_ATTRIBUER', max_length=15)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frais_calcules_centimes', models.PositiveIntegerField(default=0)),
                ('remuneration_livreur_centimes', models.PositiveIntegerField(default=0)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('date_estimee', models.DateTimeField(blank=True, null=True)),
                ('date_reelle', models.DateTimeField(blank=True, null=True)),
                ('code_confirmation', models.CharField(blank=True, max_length=8)),
                ('adresse_livraison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='comptes.adresse')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='comptes.livreur')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='livraisons.tournee')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('codes_postaux', models.TextField(help_text='Separes par des virgules.')),
                ('frais_base_centimes', models.PositiveIntegerField(default=0)),
                ('seuil_gratuite_centimes', models.PositiveIntegerField(blank=True, help_text='Au-dela de ce montant, la livraison est offerte (D-11).', null=True)),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='livraisons.entrepot')),
            ],
            options={
                'verbose_name': 'zone de livraison',
                'verbose_name_plural': 'zones de livraison',
            },
        ),
        migrations.AddField(
            model_name='tournee',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='livraisons.zonelivraison'),
        ),
        migrations.CreateModel(
            name='TentativeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentative', models.PositiveSmallIntegerField()),
                ('resultat', models.CharField(choices=[('LIVREE', 'Livree'), ('CLIENT_ABSENT', 'Client absent'), ('ADRESSE_INTROUVABLE', 'Adresse introuvable'), ('REFUSEE', 'Refusee par le client')], max_length=25)),
                ('commentaire', models.TextField(blank=True)),
                ('preuve_url', models.URLField(blank=True, help_text='Photo de depot ou signature.')),
                ('position_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('position_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='livraisons.livraison')),
            ],
            options={
                'ordering': ['numero_tentative'],
                'constraints': [models.UniqueConstraint(fields=('livraison', 'numero_tentative'), name='numero_tentative_unique')],
            },
        ),
        migrations.CreateModel(
            name='ArretTournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('A_FAIRE', 'A faire'), ('LIVRE', 'Livre'), ('ECHOUE', 'Echoue'), ('REPORTE', 'Reporte')], default='A_FAIRE', max_length=10)),
                ('heure_estimee', models.DateTimeField(blank=True, null=True)),
                ('heure_reelle', models.DateTimeField(blank=True, null=True)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arret', to='livraisons.livraison')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='livraisons.tournee')),
            ],
            options={
                'ordering': ['ordre'],
                'constraints': [models.UniqueConstraint(fields=('tournee', 'ordre'), name='ordre_arret_unique')],
            },
        ),
    ]
